# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cosine_similarity_pb2 as cosine__similarity__pb2


class CosineSimServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calc_cosine_sim = channel.unary_unary(
                '/cosine_sim.CosineSimService/calc_cosine_sim',
                request_serializer=cosine__similarity__pb2.CosineSimRequest.SerializeToString,
                response_deserializer=cosine__similarity__pb2.CosineSimResponse.FromString,
                )


class CosineSimServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calc_cosine_sim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosineSimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calc_cosine_sim': grpc.unary_unary_rpc_method_handler(
                    servicer.calc_cosine_sim,
                    request_deserializer=cosine__similarity__pb2.CosineSimRequest.FromString,
                    response_serializer=cosine__similarity__pb2.CosineSimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosine_sim.CosineSimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CosineSimService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calc_cosine_sim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cosine_sim.CosineSimService/calc_cosine_sim',
            cosine__similarity__pb2.CosineSimRequest.SerializeToString,
            cosine__similarity__pb2.CosineSimResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
